### ISSUE TITLE
Design the payments page 

### ISSUE THREAD

**Issue by Ayonijakaushik19** [QAZIMAAZARSHAD/Apni-Dukaan#140] opened 2021-07-18 03:07 UTC
The payments page should include policies related to payment on Apni Dukaan.

Like what are the ways to make payment, our partner banks, etc.

Refer to this to have an idea -> https://www.flipkart.com/pages/payments

Page must follow the theme of the website.

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-18 04:20
@Ayonijakaushik19 I will assign you this when you resolve the other assigned issues.

**Comment by K-jais** [comment] 2021-07-23 10:12
Please assign this issue to me. I will handle the payment gateway functionality in it.

**Comment by K-jais** [comment] 2021-07-23 10:13
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-25 04:42
@K-jais I think you never read the issue description.

**Comment by K-jais** [comment] 2021-07-25 06:04
Ok I have made the wrong page as per the discription of the issue but still that page is needed in your website.
So should I make the PR of the payments page or should I delete it.
@QAZIMAAZARSHAD

**Comment by K-jais** [comment] 2021-07-25 06:06
I will make that policy page as well but that payments page is still needed in this project. Isn't it?
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-25 06:12
> I will make that policy page as well but that payments page is still needed in this project. Isn't it?
> @QAZIMAAZARSHAD

Yes.
But the issue is already open, and someone is working on it.

**Comment by K-jais** [comment] 2021-07-25 06:19
Ok then can you ask her for any updates regarding that as it's been 3-4 days since her PR has been rejected for the same.  And mine page is ready to be merged in your project with a better UI.
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-25 06:28
> Ok then can you ask her for any updates regarding that as it's been 3-4 days since her PR has been rejected for the same. And mine page is ready to be merged in your project with a better UI.
> @QAZIMAAZARSHAD

Fine make a PR.

But you have not linked the payments page anywhere.

When the user clicks on the buy now in my cart page it should be redirected to the payments page.

**Comment by K-jais** [comment] 2021-07-25 06:37
Ok ok I will make that PR and add the links for it in there.

**Closed** 2021-08-01 08:38 UTC
Labels: DCP21, enhancement, 🟩 Level1
